# Generated by Django 3.0.4 on 2020-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='website',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
