# Generated by Django 3.0.4 on 2020-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_office_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='website',
            field=models.CharField(max_length=20),
        ),
    ]
