# Generated by Django 3.0.4 on 2020-05-03 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=120, verbose_name='Enter your first name:')),
                ('date_selected', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=9)),
                ('confirmed', models.BooleanField(default=False)),
                ('choice', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
