# Generated by Django 3.0.4 on 2020-04-24 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200424_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=120, verbose_name='Enter your first name:')),
                ('date_selected', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=9)),
                ('confirmed', models.BooleanField(default=False)),
                ('choice', models.CharField(max_length=120)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Office')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
